CHUNK_SIZE = 64

TILES = {
    "deep_ocean": (51, 112, 204),
    "close_ocean": (64, 132, 226),
    "shallow_waters": (85, 174, 240),
    "sand": (247, 232, 152),
    "soil_low": (226, 147, 75),
    "soil_high": (182, 111, 58),
    "soil_low:grass_low": (126, 175, 70),
    "soil_high:grass_high": (95, 131, 60),
    "soil_low:mushroom_low": (103, 118, 66),
    "soil_high:mushroom_high": (85, 99, 56),
    "soil_low:corrupted_low": (111, 85, 108),
    "soil_high:corrupted_high": (83, 63, 81),
    "soil_low:infernal_low": (156, 54, 38),
    "soil_high:infernal_high": (104, 55, 45),
    "soil_low:candy_low": (255, 150, 176),
    "soil_high:candy_high": (251, 135, 164),
    "soil_low:crystal_low": (104, 234, 222),
    "soil_high:crystal_high": (95, 214, 203),
    "soil_low:permafrost_low": (153, 188, 219),
    "soil_high:permafrost_high": (180, 207, 229),
    "soil_low:savanna_low": (240, 177, 33),
    "soil_high:savanna_high": (207, 147, 27),
    "soil_low:enchanted_low": (140, 220, 106),
    "soil_high:enchanted_high": (118, 177, 83),
    "soil_low:swamp_low": (77, 72, 62),
    "soil_high:swamp_high": (69, 62, 52),
    "soil_low:jungle_low": (70, 160, 82),
    "soil_high:jungle_high": (31, 112, 32),
    "soil_low:desert_low": (232, 199, 110),
    "soil_high:desert_high": (225, 186, 90),
    "soil_low:lemon_low": (209, 231, 113),
    "soil_high:lemon_high": (138, 207, 85),
    "soil_low:waste_low": (132, 147, 113),
    "soil_high:waste_high": (108, 119, 89),
    "soil_low:tumor_low": (253, 24, 99),
    "soil_high:tumor_high": (237, 81, 130),
    "soil_low:biomass_low": (65, 168, 64),
    "soil_high:biomass_high": (69, 200, 66),
    "soil_low:pumpkin_low": (105, 108, 2),
    "soil_high:pumpkin_high": (143, 147, 57),
    "soil_low:cybertile_low": (133, 136, 134),
    "soil_high:cybertile_high": (158, 166, 163),
    "lava3": (255, 222, 0),
    "lava2": (255, 172, 0),
    "lava1": (255, 103, 0),
    "lava0": (246, 45, 20),
    "pit_deep_ocean:tnt": (163, 0, 0),
    "pit_deep_ocean:water_bomb": (109, 0, 205),
    "pit_deep_ocean:tnt_timed": (126, 0, 0),
    "pit_deep_ocean:landmine": (153, 0, 0),
    "pit_deep_ocean:fuse": (131, 76, 76),
    "pit_deep_ocean:fireworks": (180, 61, 204),
    "pit_deep_ocean:field": (168, 102, 58),
    "pit_deep_ocean:road": (188, 149, 121),
    "hills": (91, 94, 92),
    "mountains": (65, 69, 69),
    "grey_goo": (87, 91, 136),
}
TILES_TUPLE = tuple(TILES)

MAP_TEMPLATE = {
    "saveVersion": 13,
    "width": 0,
    "height": 0,
    "mapStats": {
        "name": "Define Imagination",
        "description": "",
        "worldTime": 0.0,
        "era_id": "age_hope",
        "era_next_id": "age_sun",
        "era_month_next": 3120,
    },
    "worldLaws": {
        "list": (
            {"name": "world_law_diplomacy"},
            {"name": "world_law_peaceful_monsters", "boolVal": False},
            {"name": "world_law_hunger"},
            {"name": "world_law_vegetation_random_seeds"},
            {"name": "world_law_vegetation_seeds"},
            {"name": "world_law_grow_minerals"},
            {"name": "world_law_grow_grass"},
            {"name": "world_law_biome_overgrowth"},
            {"name": "world_law_kingdom_expansion"},
            {"name": "world_law_old_age"},
            {"name": "world_law_animals_spawn"},
            {"name": "world_law_animals_babies"},
            {"name": "world_law_rebellions"},
            {"name": "world_law_border_stealing"},
            {"name": "world_law_erosion"},
            {"name": "world_law_forever_lava", "boolVal": False},
            {"name": "world_law_disasters_nature"},
            {"name": "world_law_disasters_other"},
            {"name": "world_law_angry_civilians", "boolVal": False},
            {"name": "world_law_civ_babies"},
            {"name": "world_law_forever_tumor_creep", "boolVal": False},
            {"name": "world_law_civ_army"},
            {"name": "world_law_civ_limit_population_100", "boolVal": False},
            {"name": "age_hope"},
            {"name": "age_sun"},
            {"name": "age_dark"},
            {"name": "age_tears"},
            {"name": "age_moon"},
            {"name": "age_chaos"},
            {"name": "age_wonders"},
            {"name": "age_ice"},
            {"name": "age_ash"},
            {"name": "age_despair"},
        ),
    },
    "tileMap": (),
    "tileArray": (),
    "tileAmounts": (),
    "fire": (),
    "conwayEater": (),
    "conwayCreator": (),
    "frozen_tiles": (),
    "tiles": (),
    "cities": (),
    "actors_data": (),
    "buildings": (),
    "kingdoms": (),
    "clans": (),
    "alliances": (),
    "wars": (),
    "plots": (),
    "relations": (),
    "cultures": (),
}
